# Generated by Django 6.0.6 on 2026-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingtest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
